### ISSUE TITLE
Command prompt error

### ISSUE THREAD

**Issue by BingoFishy** [MythicManiac/Keyboard-Minigames#4] opened 2016-03-21 01:55 UTC
"Windows cannot find keyboardminigames.exe. Please make sure you typed the name correctly and try again." This happens every time I try to launch the program using the keyboard, but it works fine manually. I have carefully followed all instructions correctly. Twice.

On another note, I can't launch it using the script within the batch file. Only by clicking on it (the batch file).

**Comment by MythicManiac** [comment] 2016-03-21 12:41
Just to confirm:
- You have downloaded the [latest](https://github.com/MythicManiac/Keyboard-Minigames/releases/tag/1.0.2) release
- You have a file called `SnakeGame.bat` and `KeyboardMinigames.exe` in the same folder

This is what the folder you're launching the script from should look like:
![image](https://cloud.githubusercontent.com/assets/8225825/13918923/fdf2ee5e-ef72-11e5-8ad9-3cee467a5dae.png)

**Comment by BingoFishy** [comment] 2016-03-21 19:05
Yes; this is correct.

**Comment by MythicManiac** [comment] 2016-03-21 19:08
> I can't launch it using the script within the batch file.

What exactly are you referring to with this?

As I understood it, it works if you run the `SnakeGame.bat` by clicking it. Is this correct?

**Comment by MythicManiac** [comment] 2016-03-21 19:09
Could you also include the directory path of the `SnakeGame.bat` file, since it might be related.

**Comment by BingoFishy** [comment] 2016-03-22 00:06
C:\Users[User]\Downloads\KeyboardMinigames\KeyboardMinigames\SnakeGame.bat

**Comment by MythicManiac** [comment] 2016-03-26 12:33
There seems to be an issue with relative path finding. This can be fixed by using an absolute path to the `.exe` file, but doing that would be just a workaround—not a fix.

I wrote a [DebugScript.zip](https://github.com/MythicManiac/Keyboard-Minigames/files/190485/DebugScript.zip) that should help debugging the issue.

Could you place the `Debug.bat` from that `.zip` in the same folder where you have the `SnakeGame.bat`. After you've done this, run it once just by double clicking it, and then a second time by assigning it to a button in the CUE the same way you'd do for the snake game.

Once you've done all that, you should have a file called `C:\KeyboardMinigamesDebug.txt`. Send that over and I'll see what I can extract from the info.

If you dislike the idea of sharing the log publicly, feel free to send it directly to my email at mythicmaniac@gmail.com. Just reply to this thread once you've done so, since that way I will notice faster.

**Comment by BingoFishy** [comment] 2016-03-26 16:18
I'm on vacation right now - but I'll do it as soon as I get back
(Thursday). Thanks for all the help with this.

**Comment by BingoFishy** [comment] 2016-04-01 20:23
Not sure if I'm doing something wrong - but it just opens a command prompt window, then closes. I don't see any new text file. 

I'm just running it by double clicking/right click -> open.
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/10874365/14219040/f5828944-f825-11e5-925f-91af3eb7e2ce.gif)

Anyways, there's a little gif of it. Apparently I can't upload MP4's but this should work fine as a demonstration.

EDIT: Also, I've tried searching for it; it's not there.

**Comment by MythicManiac** [comment] 2016-04-01 23:22
This is getting somewhat difficult to resolve through here—would you mind adding me on Skype? My Skype name is "mythicpotato".

Would be greatly appreciated.

**Comment by BingoFishy** [comment] 2016-04-01 23:43
Sounds good. I should be able to Skype tomorrow.

**Comment by MythicManiac** [comment] 2016-04-02 00:30
Issue was caused by special characters in the directory path and windows' `cd` command failing to navigate to this directory. Fixed in the newest release.

**Closed as completed by MythicManiac** 2016-04-02 00:30 UTC
Labels: bug
